version: '3'
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3001:3001"
    environment:
      - RAILS_ENV=development
      - DB_HOST=172.21.0.3
      - DB_USER=postgres
      - DB_NAME=myapp_development
networks:
  default:
    external:
      name: common_network