default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DB_HOST") %>
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") %>


test:
  <<: *default
  database: myapp_test